# -*- coding: utf-8 -*-
"""DBaaS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AvH4sS6SbINx9a47AvNHAz-jW96O8dgE
"""

import pyrebase

firebaseConfig = {
  'apiKey': "AIzaSyCG8nCS-Eqax-dUtwQKzAdpjMqX8ThBu7c",
  'authDomain': "tce-navigator.firebaseapp.com",
  'databaseURL': "https://tce-navigator-default-rtdb.asia-southeast1.firebasedatabase.app",
  'projectId': "tce-navigator",
  'storageBucket': "tce-navigator.appspot.com",
  'messagingSenderId': "938064250614",
  'appId': "1:938064250614:web:885a5bf98a4fcd40380ed7",
  'measurementId': "G-V6DJK8FJ6E"
}

firebase = pyrebase.initialize_app(firebaseConfig)

db = firebase.database()

"""INSERT DATA"""

data = {
'date': "01/04/2022",
'description': "36 hrs hackathon",
'domain': "Web Development",
'locationlink': "https://goo.gl/maps/RAmpWPKK7oFki9sK7",
'name': "hackathon"
}

db.child("Events").set(data)

d = [{
'date': "01/04/2022",
'description': "36 hrs hackathon",
'domain': "Web Development",
'locationlink': "https://goo.gl/maps/RAmpWPKK7oFki9sK7",
'name': "hackathon"
},
{
'date': "11/04/2022",
'description': "cloudathon",
'domain': "Cloud",
'locationlink': "https://goo.gl/maps/RAmpWPKK7oFki9sK7",
'name': "Cloudathon"
}]

db.child("Events").set(data)

"""UPDATE DATA"""

db.child("Events").update({'name':'Hackathon'})

"""DELETE DATA"""

db.child("Events").child("domain").remove()

"""RETRIEVE DATA"""

d = db.get()

d.val()

x = db.child('Events').get()

d.val()

